# AppVeyor build definition
# http://www.appveyor.com/docs/appveyor-yml

version: 0.1.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

environment:
  PowerShellGalleryApiKey:
    secure: rRDrp3zXv9dYV/vbDq/J8ULAnArDiJz+qJqi4pxade8NWfYFwrr5TYu116nlKmFV

install:
- ps: .\init.ps1

build_script:
- ps: |
      Invoke-psake Build -NoLogo -NoTR
      if (-not $psake.build_success) { exit 1 }

test_script:
- ps: |
      Invoke-psake Test -NoLogo -NoTR
      if (-not $psake.build_success) { exit 1 }

deploy_script:
- ps: |
      Invoke-psake Publish -NoLogo -NoTR
      if (-not $psake.build_success) { exit 1 }
